name: Build and Publish Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish Python
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Install Spaces
        uses: work-spaces/install-spaces@v0.8.11-beta0
      
      - name: Test Spaces
        run: spaces --version

      - name: Clone Tools Workspaces Repo
        uses: actions/checkout@v2
        with:
          repository: work-spaces/tools-workspaces
    
      - name: Spaces Checkout
        run: spaces checkout --script=tools-workspaces/python.star --name=build-python

      - name: Build Python
        run: (cd build-python; spaces run)
