name: Build and Publish Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish Python
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Install Spaces
        uses: work-spaces/install-spaces@v0.8.14
      
      - name: Test Spaces
        run: spaces --version

      - name: Clone Tools Workspaces Repo
        run: git clone --depth=1 https://github.com/work-spaces/tools-workspaces --single-branch --branch=main
    
      - name: Spaces Checkout
        run: spaces checkout --script=tools-workspaces/python.star --name=build-python

      - name: Build Python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd build-python && spaces run
